//! Tab identity, cross-thread event types, and PTY communication bridges.
//!
//! `TabId` uniquely identifies a tab across the application lifetime.
//! `TermEvent` is the winit user event type — background threads send
//! these to the event loop for dispatch. `EventProxy` bridges terminal
//! events to winit. `Notifier` bridges keyboard input to the PTY thread.

// Tab types are wired into the event loop and PTY spawning in later
// subsections of Section 04. In test builds the tests exercise all
// public items, so `#[expect(dead_code)]` would produce unfulfilled
// warnings.
#![allow(dead_code, reason = "tab types wired into event loop in 4.5+")]

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc;

use winit::event_loop::EventLoopProxy;

use oriterm_core::{Event, EventListener};

use crate::pty::Msg;

/// Unique identifier for a tab.
///
/// Generated by an atomic counter so IDs are unique within a process.
/// The inner value is opaque — callers should not rely on ordering or gaps.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TabId(u64);

impl TabId {
    /// Generate the next unique tab ID.
    ///
    /// Thread-safe. IDs are monotonically increasing but may have gaps
    /// if tabs are created concurrently.
    pub fn next() -> Self {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        Self(COUNTER.fetch_add(1, Ordering::Relaxed))
    }
}

/// Events sent from background threads to the winit event loop.
///
/// The PTY reader thread and child-watcher thread produce these.
/// The event loop dispatches them to the appropriate tab handler.
#[derive(Debug)]
pub enum TermEvent {
    /// A terminal state-machine event from the PTY reader thread.
    ///
    /// Wraps `oriterm_core::Event` with the originating tab's identity
    /// so the event loop knows which tab to update.
    Terminal {
        /// Which tab produced this event.
        tab_id: TabId,
        /// The terminal event (wakeup, title change, bell, etc.).
        event: Event,
    },
}

/// Bridges terminal events to the winit event loop.
///
/// Created per-tab. The PTY reader thread calls
/// [`EventListener::send_event`] on this to wake the main thread.
/// Send errors are silently ignored (the window may have closed).
pub struct EventProxy {
    /// Winit's thread-safe event sender.
    proxy: EventLoopProxy<TermEvent>,
    /// Which tab this proxy belongs to.
    tab_id: TabId,
}

impl EventProxy {
    /// Create a new event proxy for the given tab.
    pub fn new(proxy: EventLoopProxy<TermEvent>, tab_id: TabId) -> Self {
        Self { proxy, tab_id }
    }
}

impl EventListener for EventProxy {
    fn send_event(&self, event: Event) {
        let _ = self.proxy.send_event(TermEvent::Terminal {
            tab_id: self.tab_id,
            event,
        });
    }
}

/// Sends input and commands to the PTY reader thread.
///
/// All messages go through the channel to the [`PtyEventLoop`](crate::pty::event_loop::PtyEventLoop).
pub struct Notifier {
    /// Channel sender to the PTY reader thread.
    tx: mpsc::Sender<Msg>,
}

impl Notifier {
    /// Create a new notifier wrapping the given channel sender.
    pub fn new(tx: mpsc::Sender<Msg>) -> Self {
        Self { tx }
    }

    /// Send raw bytes to the PTY (keyboard input, escape responses).
    pub fn notify(&self, bytes: &[u8]) {
        if bytes.is_empty() {
            return;
        }
        let _ = self.tx.send(Msg::Input(bytes.to_vec()));
    }

    /// Resize the PTY and terminal grid.
    pub fn resize(&self, rows: u16, cols: u16) {
        let _ = self.tx.send(Msg::Resize { rows, cols });
    }

    /// Request the reader thread to shut down.
    pub fn shutdown(&self) {
        let _ = self.tx.send(Msg::Shutdown);
    }
}

#[cfg(test)]
mod tests;
