//! Binary test fixtures embedded via `include_bytes!`.
//!
//! Consumers read these as `&'static [u8]` without touching the filesystem,
//! so tests are deterministic across working-directory variation and do not
//! depend on `CARGO_MANIFEST_DIR` expansion at the call site.

/// TrueType fixture for the §11.2 font-precedence tests.
///
/// Advertises coverage of one codepoint per subcell-glyph family (box
/// drawing, block elements, quadrants, sextants, octants, braille) and
/// renders a solid filled rectangle for each one. Cell metrics match
/// `JetBrains Mono` (the embedded default) so injected-font and
/// embedded-font scenarios share the same viewport dimensions.
///
/// Consumed by the `oriterm` crate's precedence tests, which inject this
/// font into `VisualSpecHarness` via
/// `GoldenLaneConfig::with_font_override` and assert the resulting frame
/// matches the canonical Canvas-rendered golden. A pass proves the
/// built-in renderer is unconditionally selected over the configured
/// font for every subcell-glyph codepoint range.
///
/// Regenerated by
/// `crates/oriterm_test_support/tests/fixtures/fonts/generate_subcell_precedence_test.py`.
pub const SUBCELL_PRECEDENCE_TEST_FONT: &[u8] =
    include_bytes!("../tests/fixtures/fonts/subcell-precedence-test.ttf");

/// Build a smoothly varying RGBA gradient at `width × height` pixels.
///
/// Produces deterministic output for given dimensions: red channel
/// scales with x, green with y, blue with `x + y`. Alpha is 0xFF. The
/// pattern represents high inter-pixel correlation, exercising
/// inflate decoders at realistic compression ratios.
///
/// Used by kitty-decode bench fixtures and prepare-helper roundtrip
/// tests so both sites share one fixture generator.
pub fn xray_gradient_rgba(width: usize, height: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(width * height * 4);
    for y in 0..height {
        for x in 0..width {
            let r = ((x * 256 / width) & 0xFF) as u8;
            let g = ((y * 256 / height) & 0xFF) as u8;
            let b = ((x + y) & 0xFF) as u8;
            out.extend_from_slice(&[r, g, b, 0xFF]);
        }
    }
    out
}
