//! Key event encoding for terminal input (legacy xterm, Kitty protocol).
//!
//! Converts winit key events into byte sequences understood by terminal
//! applications. The dispatcher chooses between Kitty keyboard protocol
//! (CSI u format) and legacy xterm encoding based on the active terminal mode.

mod kitty;
mod legacy;

use bitflags::bitflags;
use winit::keyboard::{Key, KeyCode, KeyLocation, ModifiersState, PhysicalKey};

use oriterm_core::TermMode;

/// Key event type for Kitty keyboard protocol.
///
/// Legacy encoding only processes `Press` events. Kitty protocol uses all
/// three when `REPORT_EVENT_TYPES` is active.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyEventType {
    /// Initial key press.
    Press,
    /// Held key repeating.
    Repeat,
    /// Key released.
    Release,
}

bitflags! {
    /// Keyboard modifiers for key events.
    ///
    /// Bit layout matches the xterm modifier parameter encoding:
    /// Shift=1, Alt=2, Ctrl=4, Super=8. The parameter sent to the terminal
    /// is `1 + bits` (so Ctrl+Shift = 1 + 1 + 4 = 6).
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct Modifiers: u8 {
        /// Shift key held.
        const SHIFT   = 0b0001;
        /// Alt (Meta/Option) key held.
        const ALT     = 0b0010;
        /// Control key held.
        const CONTROL = 0b0100;
        /// Super (Windows/Command) key held.
        const SUPER   = 0b1000;
    }
}

impl Modifiers {
    /// Encode as xterm modifier parameter (`1 + bitmask`).
    ///
    /// Returns 0 when no modifiers are active (caller should omit the parameter).
    pub(crate) fn xterm_param(self) -> u8 {
        if self.is_empty() { 0 } else { self.bits() + 1 }
    }
}

impl From<ModifiersState> for Modifiers {
    fn from(m: ModifiersState) -> Self {
        let mut mods = Self::empty();
        mods.set(Self::SHIFT, m.shift_key());
        mods.set(Self::ALT, m.alt_key());
        mods.set(Self::CONTROL, m.control_key());
        mods.set(Self::SUPER, m.super_key());
        mods
    }
}

/// Bundled key event for encoding.
///
/// Groups key event parameters into a single struct to keep the public
/// API clean (avoids clippy `too_many_arguments`).
pub struct KeyInput<'a> {
    /// The logical key identifier (named key or character).
    pub key: &'a Key,
    /// Active modifier keys.
    pub mods: Modifiers,
    /// Current terminal mode flags.
    pub mode: TermMode,
    /// Text generated by the key (from winit, after dead keys/IME).
    pub text: Option<&'a str>,
    /// Physical key location (Standard, Left, Right, Numpad).
    pub location: KeyLocation,
    /// Whether this is a press, repeat, or release event.
    pub event_type: KeyEventType,
    /// US keyboard layout codepoint for the physical key.
    ///
    /// Used by `REPORT_ALTERNATE_KEYS` (Kitty flag 4) to report the
    /// key that corresponds to the physical position on a US layout.
    /// `None` when unavailable or when it matches the logical key.
    pub alternate_key: Option<u32>,
}

/// Encode a key event into bytes to send to the PTY.
///
/// Returns an empty `Vec` if the key should not produce output (bare modifier
/// presses, unhandled keys, or suppressed release events).
///
/// Dispatch priority:
/// 1. **Kitty keyboard protocol** — when any `KITTY_KEYBOARD_PROTOCOL` flag is set.
/// 2. **`APP_KEYPAD` numpad** — numpad keys in application keypad mode.
/// 3. **Legacy xterm** — standard VT/xterm escape sequences.
pub fn encode_key(input: &KeyInput<'_>) -> Vec<u8> {
    // Kitty keyboard protocol takes priority when any flag is set.
    if input.mode.intersects(TermMode::KITTY_KEYBOARD_PROTOCOL) {
        return kitty::encode_kitty(input);
    }

    // Legacy mode only sends on press.
    if input.event_type == KeyEventType::Release {
        return Vec::new();
    }

    // `APP_KEYPAD` numpad keys.
    if input.location == KeyLocation::Numpad && input.mode.contains(TermMode::APP_KEYPAD) {
        if let Some(bytes) = legacy::encode_numpad_app(input.key) {
            return bytes;
        }
    }

    legacy::encode_legacy(input.key, input.mods, input.mode, input.text)
}

/// Map a physical key to its US keyboard layout codepoint.
///
/// Returns `None` for non-character physical keys (modifiers, function keys)
/// or when the physical key matches the logical key (no layout difference).
/// Only character keys that differ between keyboard layouts benefit from
/// `REPORT_ALTERNATE_KEYS` reporting.
pub fn physical_key_to_us_codepoint(physical: PhysicalKey, logical: &Key) -> Option<u32> {
    let code = match physical {
        PhysicalKey::Code(c) => c,
        PhysicalKey::Unidentified(_) => return None,
    };
    let us_cp = keycode_to_us_char(code)?;

    // Only report when the alternate differs from the logical key.
    let logical_cp = match logical {
        Key::Character(s) => {
            let mut chars = s.chars();
            let c = chars.next()?;
            if chars.next().is_some() {
                return None;
            }
            c as u32
        }
        _ => return None, // Named keys don't need alternate reporting.
    };

    if us_cp == logical_cp {
        None
    } else {
        Some(us_cp)
    }
}

/// Map a `KeyCode` (physical position) to US QWERTY character codepoint.
fn keycode_to_us_char(code: KeyCode) -> Option<u32> {
    Some(match code {
        // Letters (lowercase).
        KeyCode::KeyA => b'a' as u32,
        KeyCode::KeyB => b'b' as u32,
        KeyCode::KeyC => b'c' as u32,
        KeyCode::KeyD => b'd' as u32,
        KeyCode::KeyE => b'e' as u32,
        KeyCode::KeyF => b'f' as u32,
        KeyCode::KeyG => b'g' as u32,
        KeyCode::KeyH => b'h' as u32,
        KeyCode::KeyI => b'i' as u32,
        KeyCode::KeyJ => b'j' as u32,
        KeyCode::KeyK => b'k' as u32,
        KeyCode::KeyL => b'l' as u32,
        KeyCode::KeyM => b'm' as u32,
        KeyCode::KeyN => b'n' as u32,
        KeyCode::KeyO => b'o' as u32,
        KeyCode::KeyP => b'p' as u32,
        KeyCode::KeyQ => b'q' as u32,
        KeyCode::KeyR => b'r' as u32,
        KeyCode::KeyS => b's' as u32,
        KeyCode::KeyT => b't' as u32,
        KeyCode::KeyU => b'u' as u32,
        KeyCode::KeyV => b'v' as u32,
        KeyCode::KeyW => b'w' as u32,
        KeyCode::KeyX => b'x' as u32,
        KeyCode::KeyY => b'y' as u32,
        KeyCode::KeyZ => b'z' as u32,
        // Digits.
        KeyCode::Digit1 => b'1' as u32,
        KeyCode::Digit2 => b'2' as u32,
        KeyCode::Digit3 => b'3' as u32,
        KeyCode::Digit4 => b'4' as u32,
        KeyCode::Digit5 => b'5' as u32,
        KeyCode::Digit6 => b'6' as u32,
        KeyCode::Digit7 => b'7' as u32,
        KeyCode::Digit8 => b'8' as u32,
        KeyCode::Digit9 => b'9' as u32,
        KeyCode::Digit0 => b'0' as u32,
        // Punctuation (US layout).
        KeyCode::Minus => b'-' as u32,
        KeyCode::Equal => b'=' as u32,
        KeyCode::BracketLeft => b'[' as u32,
        KeyCode::BracketRight => b']' as u32,
        KeyCode::Backslash => b'\\' as u32,
        KeyCode::Semicolon => b';' as u32,
        KeyCode::Quote => b'\'' as u32,
        KeyCode::Backquote => b'`' as u32,
        KeyCode::Comma => b',' as u32,
        KeyCode::Period => b'.' as u32,
        KeyCode::Slash => b'/' as u32,
        _ => return None,
    })
}

#[cfg(test)]
mod tests;
