#!/usr/bin/env bash
# tp-help-sentinels.sh — CANONICAL definition of the /tp-help concat-mode
# attribution sentinel format. Source this file from any shell consumer
# that needs to emit or grep for the sentinels; do NOT hardcode the
# literal strings elsewhere.
#
# Why this file exists (§07.3 SSOT fix):
# Codex AND gemini reviewers both flagged during the §07.3 TPR pass that
# the sentinel format was hardcoded in at least 4 places. Any rename
# would require coordinated edits across all those sites, risking DRIFT
# per impl-hygiene.md §SSOT. This file is the Single Source of Truth.
#
# Why PER-INVOCATION TOKENS (§07.3 TPR v2 fix — EXPOSURE finding):
# The second-pass TPR surfaced a real spoofing vulnerability in the
# original static sentinel format (`<!-- tp-help-reviewer: codex -->`):
# if a reviewer's prose quoted the literal closing sentinel (e.g., when
# discussing the tp-help format itself), the concat output would contain
# two identical close markers — a naive consumer doing greedy open-to-
# close matching would terminate the reviewer's block prematurely. Both
# reviewers flagged this as EXPOSURE. The plan anticipated the fix
# (`plans/dual-tpr-gemini/section-07-tp-help.md` line ~776: "add a
# per-invocation random suffix to the sentinel").
#
# The per-invocation token is generated by `tp_help_make_token` AFTER
# the reviewer prompt is sent — meaning the reviewer CANNOT embed the
# token in its body at generation time. Cooperative reviewers quoting
# the STATIC sentinel prefix in explanations no longer collide because
# their quoted sentinel has no matching token. An adversarial reviewer
# could try to guess the token, but /dev/urandom gives 6 bytes (48 bits)
# of entropy — brute-force collision probability is negligible.
#
# Usage:
#   source "$(dirname "$0")/tp-help-sentinels.sh"
#   token=$(tp_help_make_token)
#   tp_help_emit_block codex "$token" "$body" >> "$output"
#   tp_help_emit_block gemini "$token" "$body" >> "$output"
#   # Both blocks from the same run share the same token.

# Idempotent source guard (§07.3 TPR v2 fix — both reviewers agreed).
# The original `readonly` declarations caused double-source to fail
# under `set -e`. Guard makes second source a no-op.
if [[ -n "${TP_HELP_SENTINEL_GUARD:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi
TP_HELP_SENTINEL_GUARD=1

# Canonical prefix for leakage detection. A consumer that wants to
# assert "no sentinel of any kind leaked into this file" should grep
# for this substring, which matches all variants (codex/gemini,
# open/close, any token). This is what `validate-tp-help-consumers.sh`
# uses for its cross-cutting negative pin. The prefix is deliberately
# short and unambiguous.
TP_HELP_SENTINEL_PREFIX='tp-help-reviewer:'

# tp_help_make_token — generate a unique per-invocation token.
# Returns a hex string (12 chars = 48 bits entropy from /dev/urandom),
# or a timestamp+pid+RANDOM fallback if /dev/urandom + od + tr are not
# ALL available. The fallback must never fail — this function is
# load-bearing for the spoofing-resistance design and MUST NOT break.
#
# §07.3 TPR v3 fix (codex GAP): the previous version only checked
# /dev/urandom readability, not whether `od` and `tr` were actually
# available on PATH. Under `PATH=/tmp` the function silently returned
# empty with rc=127, contradicting the "must not break" contract in
# the docstring. Codex verified this empirically. The fix now also
# checks for the tools via `command -v` before trusting the
# /dev/urandom path.
#
# The token MUST be generated AFTER the reviewer prompts have been
# written — that's the whole point of the spoofing-resistance design.
# Generating it earlier (e.g., at shell startup) would create a window
# where a cooperative caller could accidentally pass the token into
# the reviewer prompt, reintroducing the vulnerability.
tp_help_make_token() {
  if [[ -r /dev/urandom ]] && command -v od >/dev/null 2>&1 && command -v tr >/dev/null 2>&1; then
    od -An -tx1 -N 6 /dev/urandom | tr -d ' \n'
    return 0
  fi
  # Fallback: timestamp+pid+RANDOM. printf is a bash builtin, so this
  # path works even under `PATH=/tmp` where external tools are missing.
  printf '%s-%s-%s' "${EPOCHSECONDS:-$(date +%s 2>/dev/null || printf 'na')}" "$$" "${RANDOM:-0}"
}

# tp_help_emit_block — write one attributed reviewer block to stdout.
# Args:
#   $1 — reviewer name: "codex" or "gemini"
#   $2 — per-invocation token (from tp_help_make_token)
#   $3 — body text (raw reviewer response)
#
# Emits:
#   <!-- tp-help-reviewer: {reviewer} @{token} -->
#   {body}
#   <!-- /tp-help-reviewer: {reviewer} @{token} -->
#
# The token appears in BOTH the open and close markers so consumers can
# unambiguously pair them by token — even if a reviewer's body contains
# a sentinel-looking string from a DIFFERENT invocation (e.g., cited
# from documentation), the quoted token won't match the current run's
# token and the consumer's matcher will skip it.
#
# Consumers that want human-visible labels MAY add a single prose line
# immediately after the opening sentinel (e.g., `**Codex says:**`), but
# the token-embedded sentinels themselves are the authoritative
# machine-readable attribution.
tp_help_emit_block() {
  local reviewer="$1" token="$2" body="$3"
  local name
  case "$reviewer" in
    codex|gemini)
      name="$reviewer"
      ;;
    *)
      printf 'tp_help_emit_block: unknown reviewer: %s (must be codex|gemini)\n' "$reviewer" >&2
      return 2
      ;;
  esac
  if [[ -z "$token" ]]; then
    printf 'tp_help_emit_block: token argument is required (call tp_help_make_token first)\n' >&2
    return 2
  fi
  printf '<!-- tp-help-reviewer: %s @%s -->\n%s\n<!-- /tp-help-reviewer: %s @%s -->\n' \
    "$name" "$token" "$body" "$name" "$token"
}
