//! Unique identifier for compositor layers.
//!
//! Lives in `geometry` (alongside `Point`, `Rect`, `Size`) because it is a
//! primitive ID type consumed by both `animation` and `compositor`. Keeping
//! it here breaks the bidirectional import cycle between those modules.

use std::fmt;

/// Unique identifier for a compositor layer.
///
/// Generated by [`LayerTree`](crate::compositor::layer_tree::LayerTree) via its
/// internal counter. Distinct from `WidgetId` — layers are compositor
/// primitives, not widget-tree nodes.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct LayerId(u64);

impl LayerId {
    /// Creates a `LayerId` from a raw value.
    ///
    /// Used by `LayerTree` to allocate IDs from its counter.
    pub fn new(id: u64) -> Self {
        Self(id)
    }

    /// Returns the raw numeric value.
    pub fn raw(self) -> u64 {
        self.0
    }
}

impl fmt::Debug for LayerId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "LayerId({})", self.0)
    }
}

impl fmt::Display for LayerId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
