//! iTerm2 inline image visual pilot — minimal 1×1 PNG at the cursor.
//!
//! Catalog row: `ITERM2-1337-FILE-PNG`
//! Apex: `GoldenImage`
//!
//! Drives `OSC 1337 ; File=inline=1:<minimal-png-b64> ST` through every
//! visual rung and asserts each rung passes. Establishes the §14.1
//! per-format texture-render dual-gate (state-snapshot + golden) for
//! the PNG arm of the iTerm2 inline image protocol.

use oriterm_test_support::spec_chain::{
    ApexLayer, FrameInputExpectation, GoldenExpectation, GpuInstanceExpectation, RungName,
    ScenarioExpectations, SpecScenario, TextureExpectation,
};

use super::super::visual_harness::VisualSpecHarness;

/// `OSC 1337 ; File=inline=1:<b64> ST` with the b64 of a 1×1 opaque-red
/// RGBA PNG produced by the `image` crate (encoded=73 bytes, b64.len=100).
///
/// Provenance: bytes generated by feeding
/// `image::ImageBuffer::from_pixel(1, 1, Rgba([0xFF, 0x00, 0x00, 0xFF]))`
/// through `image::ImageFormat::Png`. Mirror of the runtime fixture in
/// `oriterm_core/tests/spec_chain/osc/iterm2_image.rs::fixtures::minimal_png_bytes`.
const ITERM2_PNG_BYTES: &[u8] = b"\x1b]1337;File=inline=1:iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAEElEQVR4AQEFAPr/AP8AAP8FAAH/+lyI0QAAAABJRU5ErkJggg==\x1b\\";

/// Pilot test: drives the minimal iTerm2 PNG through every visual rung.
///
/// Uses the deterministic golden lane (Section 05) via `VisualSpecHarness`.
/// The golden image is captured with `ORITERM_UPDATE_GOLDEN=1` and
/// committed under `oriterm/tests/references/`.
#[test]
fn iterm2_image_png_at_cursor_drives_every_rung_green() {
    let Some(mut harness) = VisualSpecHarness::new() else {
        eprintln!("SKIP: software rasterizer unavailable");
        return;
    };

    let scenario = SpecScenario {
        catalog_row_id: "ITERM2-1337-FILE-PNG",
        bytes: ITERM2_PNG_BYTES,
        apex_layer: ApexLayer::GoldenImage,
        setup: b"",
        expectations: ScenarioExpectations {
            frame_input: Some(FrameInputExpectation::default_grid()),
            // One image quad emitted from the iTerm2 placement at cursor.
            gpu_instance: Some(GpuInstanceExpectation::at_least(1, 0).with_images(1)),
            texture: Some(TextureExpectation {
                min_non_zero_pixels: Some(1),
                width: None,
                height: None,
            }),
            golden: Some(GoldenExpectation {
                golden_name: Some("iterm2_image_png_at_cursor"),
            }),
            ..ScenarioExpectations::default()
        },
    };

    let results = harness.run_visual_scenario(&scenario);

    for r in &results {
        assert!(
            r.passed,
            "rung {:?} failed: {}",
            r.rung_name,
            r.failure.as_deref().unwrap_or("(no message)")
        );
    }

    let rung_names: Vec<_> = results.iter().map(|r| r.rung_name).collect();
    assert_eq!(
        rung_names.len(),
        8,
        "GoldenImage apex should produce exactly 8 rung results, got: {rung_names:?}"
    );
    assert_eq!(
        *rung_names.last().unwrap(),
        RungName::GoldenImage,
        "last rung should be GoldenImage"
    );
}
