//! iTerm2 inline image visual pilot — minimal 1×1 BMP at the cursor.
//!
//! Catalog row: `ITERM2-1337-FILE-BMP`
//! Apex: `GoldenImage`
//!
//! Drives `OSC 1337 ; File=inline=1:<minimal-bmp-b64> ST` through every
//! visual rung and asserts each rung passes. Establishes the §14.1
//! per-format texture-render dual-gate for the BMP arm.

use oriterm_test_support::spec_chain::{
    ApexLayer, FrameInputExpectation, GoldenExpectation, GpuInstanceExpectation, RungName,
    ScenarioExpectations, SpecScenario, TextureExpectation,
};

use super::super::visual_harness::VisualSpecHarness;

/// `OSC 1337 ; File=inline=1:<b64> ST` with the b64 of a 1×1 opaque-red
/// RGBA BMP produced by the `image` crate (encoded=126 bytes, b64.len=168).
///
/// Provenance: bytes generated by feeding
/// `image::ImageBuffer::from_pixel(1, 1, Rgba([0xFF, 0x00, 0x00, 0xFF]))`
/// through `image::ImageFormat::Bmp`.
const ITERM2_BMP_BYTES: &[u8] = b"\x1b]1337;File=inline=1:Qk1+AAAAAAAAAHoAAABsAAAAAQAAAAEAAAABACAAAwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAD/AAD/AAAAAAAA/0JHUnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//\x1b\\";

/// Pilot test: drives the minimal iTerm2 BMP through every visual rung.
#[test]
fn iterm2_image_bmp_at_cursor_drives_every_rung_green() {
    let Some(mut harness) = VisualSpecHarness::new() else {
        eprintln!("SKIP: software rasterizer unavailable");
        return;
    };

    let scenario = SpecScenario {
        catalog_row_id: "ITERM2-1337-FILE-BMP",
        bytes: ITERM2_BMP_BYTES,
        apex_layer: ApexLayer::GoldenImage,
        setup: b"",
        expectations: ScenarioExpectations {
            frame_input: Some(FrameInputExpectation::default_grid()),
            gpu_instance: Some(GpuInstanceExpectation::at_least(1, 0).with_images(1)),
            texture: Some(TextureExpectation {
                min_non_zero_pixels: Some(1),
                width: None,
                height: None,
            }),
            golden: Some(GoldenExpectation {
                golden_name: Some("iterm2_image_bmp_at_cursor"),
            }),
            ..ScenarioExpectations::default()
        },
    };

    let results = harness.run_visual_scenario(&scenario);

    for r in &results {
        assert!(
            r.passed,
            "rung {:?} failed: {}",
            r.rung_name,
            r.failure.as_deref().unwrap_or("(no message)")
        );
    }

    let rung_names: Vec<_> = results.iter().map(|r| r.rung_name).collect();
    assert_eq!(
        rung_names.len(),
        8,
        "GoldenImage apex should produce exactly 8 rung results, got: {rung_names:?}"
    );
    assert_eq!(
        *rung_names.last().unwrap(),
        RungName::GoldenImage,
        "last rung should be GoldenImage"
    );
}
